name: studet_managment
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_bloc: ^8.0.0
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  get_it: ^7.2.0
  email_validator: ^2.0.1
  intl: ^0.17.0
  path_provider: ^2.0.9
  animated_text_kit: ^4.2.1
  equatable: ^2.0.5
  permission_handler: ^10.0.0
  contacts_service: ^0.6.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.0
  build_runner: ^2.1.7
  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true
